# Generated by Django 3.2.6 on 2021-10-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=170, verbose_name='Промо фкция')),
                ('image', models.ImageField(upload_to='promo/', verbose_name='Изображение')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.SmallIntegerField(default=0),
        ),
    ]
