# Generated by Django 3.2.6 on 2021-10-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20211004_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
